12:57:27.640 INFO Test execution started: second_test
12:57:27.641 INFO Browser: chrome
12:57:27.641 INFO Environment: test_env
12:57:27.642 INFO Using data:
    order_type: Plats
    document_type: CORRECTION OF PLAT (PL)
    num_of_pages: 1
    num_of_lots: 1
    section: GRANTOR
    first_name: First Name
    url: http://{}:{}@10.0.1.73:8001/69999/?ReturnUrl=https://crs.qa.kofile.com/69999/Account/ReturnClaim&amp;Referrer=
12:57:30.857 INFO Navigate to: 'http://User1:Automation_1_3@10.0.1.73:8001/69999/?ReturnUrl=https://crs.qa.kofile.com/69999/Account/ReturnClaim&amp;Referrer='
12:57:41.932 INFO Click addNewOrderButton
12:57:47.148 INFO Waiting for 3 seconds
12:57:50.192 INFO Click orderTypeDropdown
12:57:50.302 INFO Click //select[@id='orderTypeId']/option[text()='Plats']
12:57:57.487 INFO Click documentTypeDropdown
12:57:57.584 INFO Click //select[@id='Order_OrderItems[0]_Document_DocumentTypeId']/option[text()='CORRECTION OF PLAT (PL)']
12:57:57.666 INFO Write '1' in element numberOfPages
12:57:57.802 INFO Write '1' in element numberOfLots
12:57:57.908 INFO Click partiesTab
12:57:58.035 INFO Write 'asd' in element //input[@placeholder='First Name']
12:57:58.201 INFO Click addToOrderButton
12:57:58.270 ERROR ElementClickInterceptedException: Message: element click intercepted: Element <li id="addToOrderOuter">...</li> is not clickable at point (864, 917). Other element would receive the click: <div id="footerinner">...</div>
  (Session info: chrome=77.0.3865.120)

Traceback (most recent call last):
  File "c:\users\alexandr.may\appdata\local\programs\python\python37-32\lib\site-packages\golem\test_runner\test_runner.py", line 173, in run_test
    self.test_module.test(execution.data)
  File "C:\Users\alexandr.may\testdir\projects\some_project\tests\second_test.py", line 24, in test
    a.click(new_order_page_form.addToOrderButton)
  File "c:\users\alexandr.may\appdata\local\programs\python\python37-32\lib\site-packages\golem\actions.py", line 985, in click
    element.click()
  File "c:\users\alexandr.may\appdata\local\programs\python\python37-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "c:\users\alexandr.may\appdata\local\programs\python\python37-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "c:\users\alexandr.may\appdata\local\programs\python\python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "c:\users\alexandr.may\appdata\local\programs\python\python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <li id="addToOrderOuter">...</li> is not clickable at point (864, 917). Other element would receive the click: <div id="footerinner">...</div>
  (Session info: chrome=77.0.3865.120)


12:58:00.898 INFO Test Result: CODE ERROR
