13:34:15.717 INFO Test execution started: fee_distribution
13:34:15.718 INFO Browser: chrome
13:34:15.720 INFO Environment: test_env
13:34:15.722 INFO Using data:
    url: http://{}:{}@10.0.1.73:8001/69999/?ReturnUrl=https://crs.qa.kofile.com/69999/Account/ReturnClaim&amp;Referrer=
13:34:18.985 INFO Navigate to: 'http://User1:Automation_1_3@10.0.1.73:8001/69999/?ReturnUrl=https://crs.qa.kofile.com/69999/Account/ReturnClaim&amp;Referrer='
13:34:36.312 INFO Waiting for 3 seconds
13:34:39.349 ERROR AttributeError: module 'new_order_page_form' has no attribute 'runningManOfOrder'
Traceback (most recent call last):
  File "c:\users\alexandr.may\appdata\local\programs\python\python37-32\lib\site-packages\golem\test_runner\test_runner.py", line 173, in run_test
    self.test_module.test(execution.data)
  File "C:\Users\alexandr.may\testdir\projects\some_project\tests\fee_distribution.py", line 17, in test
    a.click(new_order_page_form.runningManOfOrder('20191001000218'))
AttributeError: module 'new_order_page_form' has no attribute 'runningManOfOrder'

13:34:41.916 INFO Test Result: CODE ERROR
