11:45:58.451 INFO Test execution started: second_test
11:45:58.452 INFO Browser: chrome-remote
11:45:58.452 INFO Environment: test_env
11:45:58.452 INFO Using data:
    order_type: Plats
    document_type: CORRECTION OF PLAT (PL)
    num_of_pages: 1
    num_of_lots: 1
    section: GRANTOR
    first_name: First Name
    alert_text: Please Enter Account OR Email OR Name
    url: http://{}:{}@10.0.1.73:8001/69999/?ReturnUrl=https://crs.qa.kofile.com/69999/Account/ReturnClaim&amp;Referrer=
11:45:59.083 ERROR UnsupportedOperation: not readable
Traceback (most recent call last):
  File "c:\users\alexandr.may\appdata\local\programs\python\python37-32\lib\site-packages\golem\test_runner\test_runner.py", line 173, in run_test
    self.test_module.test(execution.data)
  File "C:\Users\alexandr.may\testdir\projects\some_project\tests\second_test.py", line 33, in test
    dataInfile = json.loads(file.read())
io.UnsupportedOperation: not readable

11:45:59.262 INFO Test Result: CODE ERROR
