12:06:08.896 INFO Test execution started: second_test
12:06:08.897 INFO Browser: chrome
12:06:08.897 INFO Environment: test_env
12:06:08.897 INFO Using data:
    order_type: Plats
    document_type: CORRECTION OF PLAT (PL)
    num_of_pages: 1
    num_of_lots: 1
     first_name: First Name
    url: http://{}:{}@10.0.1.73:8001/69999/?ReturnUrl=https://crs.qa.kofile.com/69999/Account/ReturnClaim&amp;Referrer=
12:06:12.081 ERROR ImportError: Traceback (most recent call last):
AttributeError: 'tuple' object has no attribute 'find'

Traceback (most recent call last):
  File "c:\users\alexandr.may\appdata\local\programs\python\python37-32\lib\site-packages\golem\test_runner\test_runner.py", line 142, in import_modules
    page.split('.'))
  File "c:\users\alexandr.may\appdata\local\programs\python\python37-32\lib\site-packages\golem\test_runner\test_runner_utils.py", line 26, in import_page_into_test
    raise ImportError(error)
ImportError: Traceback (most recent call last):
AttributeError: 'tuple' object has no attribute 'find'


12:06:12.082 INFO Test Result: CODE ERROR
