17:40:29.128 INFO Test execution started: capture
17:40:29.128 INFO Browser: chrome
17:40:29.128 INFO Environment: test_env
17:40:29.129 INFO Using data:
    url: http://{}:{}@10.0.1.73:8001/69999/?ReturnUrl=https://crs.qa.kofile.com/69999/Account/ReturnClaim&amp;Referrer=
17:40:32.313 INFO Navigate to: 'http://User1:Automation_1_3@10.0.1.73:8001/69999/?ReturnUrl=https://crs.qa.kofile.com/69999/Account/ReturnClaim&amp;Referrer='
17:40:41.098 INFO Click captureTab
17:40:46.301 INFO Waiting for 3 seconds
17:40:49.483 ERROR TypeError: 'int' object is not iterable
Traceback (most recent call last):
  File "c:\users\alexandr.may\appdata\local\programs\python\python37-32\lib\site-packages\golem\test_runner\test_runner.py", line 173, in run_test
    self.test_module.test(execution.data)
  File "C:\Users\alexandr.may\testdir\projects\some_project\tests\capture.py", line 20, in test
    print(a.get_element_text(new_order_page_form.find('20191002000145')))
  File "C:\Users\alexandr.may\testdir\projects\some_project\pages\new_order_page_form.py", line 45, in find
    for i in raws():
TypeError: 'int' object is not iterable

17:40:49.891 INFO Close browser
17:40:52.098 INFO Test Result: CODE ERROR
