11:04:26.778 INFO Test execution started: second_test
11:04:26.779 INFO Browser: firefox-remote
11:04:26.779 INFO Environment: test_env
11:04:26.780 INFO Using data:
    url: http://{}:{}@10.0.1.73:8001/69999/?ReturnUrl=https://crs.qa.kofile.com/69999/Account/ReturnClaim&amp;Referrer=
11:04:28.977 INFO Navigate to: 'http://User1:Automation_1_3@10.0.1.73:8001/69999/?ReturnUrl=https://crs.qa.kofile.com/69999/Account/ReturnClaim&amp;Referrer='
11:04:44.500 ERROR ElementNotFound: Element addNewOrderButton not found using selector id:'addNewOrder'
Traceback (most recent call last):
  File "c:\users\alexandr.may\appdata\local\programs\python\python37-32\lib\site-packages\golem\test_runner\test_runner.py", line 173, in run_test
    self.test_module.test(execution.data)
  File "C:\Users\alexandr.may\testdir\projects\some_project\tests\second_test.py", line 14, in test
    a.click(home_page.addNewOrderButton)
  File "c:\users\alexandr.may\appdata\local\programs\python\python37-32\lib\site-packages\golem\actions.py", line 983, in click
    element = browser.get_browser().find(element)
  File "c:\users\alexandr.may\appdata\local\programs\python\python37-32\lib\site-packages\golem\webdriver\extended_driver.py", line 177, in find
    return common._find(self, **kwargs)
  File "c:\users\alexandr.may\appdata\local\programs\python\python37-32\lib\site-packages\golem\webdriver\common.py", line 122, in _find
    element_name, timeout, wait_displayed)
  File "c:\users\alexandr.may\appdata\local\programs\python\python37-32\lib\site-packages\golem\webdriver\common.py", line 47, in _find_webelement
    .format(element_name, selector_type, selector_value))
golem.core.exceptions.ElementNotFound: Element addNewOrderButton not found using selector id:'addNewOrder'

11:04:46.277 INFO Test Result: CODE ERROR
