13:07:16.690 INFO Test execution started: second_test
13:07:16.691 INFO Browser: chrome-remote
13:07:16.691 INFO Environment: test_env
13:07:16.692 INFO Using data:
    order_type: Plats
    document_type: LETTER (PL)
    num_of_pages: 1
    num_of_lots: 1
    section: GRANTOR
    first_name: First Name
    alert_text: Please Enter Account OR Email OR Name
    url: http://{}:{}@10.0.1.73:8001/69999/?ReturnUrl=https://crs.qa.kofile.com/69999/Account/ReturnClaim&amp;Referrer=
13:07:17.350 ERROR AttributeError: '_io.TextIOWrapper' object has no attribute 'json'
Traceback (most recent call last):
  File "c:\users\alexandr.may\appdata\local\programs\python\python37-32\lib\site-packages\golem\test_runner\test_runner.py", line 173, in run_test
    self.test_module.test(execution.data)
  File "C:\Users\alexandr.may\testdir\projects\some_project\tests\second_test.py", line 39, in test
    print(jsonpath.jsonpath(f.json(), 'key'))
AttributeError: '_io.TextIOWrapper' object has no attribute 'json'

13:07:17.542 INFO Test Result: CODE ERROR
